// src/routes/__layout.svelte
<script type="ts">
  import { onMount } from 'svelte';
  import Header from '$src/components/layout/Header.svelte'
  import Footer from '$src/components/layout/Footer.svelte'
  import near from '$src/utils/near'

  onMount(async() =>{
    $near.connect()
  })
</script>

<svelte:head>
  {#if false}
	  <link rel="stylesheet" href="/css/light-theme.css">
  {/if}
</svelte:head>

<Header />
<main>
  <div class='container' style="min-height: calc(100vh - 410px)">
    {#if $near.connected}
      <slot></slot>
    {/if}
  </div>
</main>
<Footer />

// components/layout/index.tsx
import { ReactElement } from 'react'
import Head from 'next/head'
import Header from './Header'
import Footer from './Footer'

const Layout = ({ children }: { children: ReactElement }) => {
  return (
    <>
      <Head>
        <title>Battlemon</title>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon.png" />
      </Head>
      <Header />
      
      <main>
        <div className='container'>
          {children}
        </div>
      </main>
      <Footer />
    </>
  );
};

export default Layout;
